### ISSUE TITLE
maintaining the Mac Address / Serial to an SSO acocunt data that had been assigned 

### ISSUE THREAD

**Issue by vincentchung** [Ubiquiti-Cloud/tic#5]
we have the api to assign mac address to an sso account in itsp_redirection api list.(https://api-docs.svc.ubnt.com/control/v1/itsp_redirection/#assign-mac-address--serial-to-an-sso-acocunt
)

Is that possible to provide the api to query all the mac address that has been assigned to the sso account?

And also modify/delete the data.

**Comment by AeroNotix** [comment]
Wrong repository.
